trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    exclude:
      - '.github'
      - docs
      - README.md
      - CHANGELOG.md
      - CONTRIBUTING.md

pr: none

variables:
  - template: variables.yml

pool:
  vmImage: $(vmImage)

steps:
  - task: UseDotNet@2
    displayName: Install .NET sdk
    inputs:
      packageType: sdk
      version: $(netSdkVersion)
  - pwsh: >
      dotnet build
      --configuration $(buildConfiguration)
      -p:Version=$(releaseVersion)
      $(projectPath)
    displayName: Build project with release version
  - pwsh: >
      dotnet pack
      --no-build
      --output "$(Build.ArtifactStagingDirectory)/packages"
      --configuration $(buildConfiguration)
      -p:Version=$(releaseVersion)
      $(projectPath)
    displayName: Create release nuget package
# Temporarily disable publishing artifacts to nuget.org
#  - pwsh: >
#      dotnet nuget push
#      $(Build.ArtifactStagingDirectory)/packages/*.nupkg
#      --api-key $(NugetApiKey)
#      --skip-duplicate
#      --source https://api.nuget.org/v3/index.json
#    displayName: Publish package to NuGet
  - pwsh: >
      dotnet nuget push
      $(Build.ArtifactStagingDirectory)/packages/*.nupkg
      --api-key $(GithubPAT)
      --skip-duplicate
      --source https://nuget.pkg.github.com/TelegramBots/index.json
    displayName: Publish package to Github NuGet feed
  - task: GitHubRelease@1
    inputs:
      action: create
      target: $(Build.SourceVersion)
      tagSource: userSpecifiedTag
      tag: v$(releaseVersion)
      tagPattern: v$(releaseVersion)
      title: v$(releaseVersion)
      githubConnection: githubRelease
      repositoryName: $(Build.Repository.Name)
      isPreRelease: $(isPreRelease)
      addChangeLog: false
      assets: $(Build.ArtifactStagingDirectory)/packages/*
    displayName: Create Github Release
